version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
